### ISSUE TITLE
Plugin loses connection when android client connects to Elk?

### ISSUE THREAD

**Issue by JonGilmore** [BioSehnsucht/ha-elkm1#3]
Everything seems to be functioning fine with the ha-elkm1 plugin until I connect my Android phone to the Elk panel (using M1 Touch Pro).  Once I do that, the following is displayed in my HA log:

```2018-02-11 18:51:33 DEBUG (Thread-23) [PyElk.Event] Parsing: '11KF00000000000009D'
2018-02-11 18:51:33 DEBUG (Thread-23) [PyElk.Elk] elk_queue_process - checking events
2018-02-11 18:51:33 DEBUG (Thread-23) [PyElk.Elk] handle_line: 11KF00000000000009D
2018-02-11 18:51:33 DEBUG (Thread-23) [PyElk.Event] Parsing: '19KC00000101120000000000013'
2018-02-11 18:51:33 DEBUG (Thread-23) [PyElk.Elk] elk_queue_process - checking events
2018-02-11 18:51:33 DEBUG (Thread-23) [PyElk.Elk] elk_queue_process - Event.EVENT_KEYPAD_STATUS_REPORT
2018-02-11 18:51:33 DEBUG (Thread-23) [PyElk.Elk] Lost connection
```

Here is my config: 

```elkm1:
  host: socket://10.10.10.10:2101
  code: !secret elk_pin
  area:
    exclude: 3-8
  zone:
    exclude: 17-24, 27-208
  output:
    exclude: 1-8, 11-208
  counter:
    include: 1
  keypad:
    include: 1-5
  task:
    exclude: 1-32
```

**Comment by BioSehnsucht** [comment]
I'll add that to the to-do list of bugs to check. Usually when it loses the connection it's not because the connection was closed, but that some part of the PyElk or ha-elkm1 code crashed due to a bug.

From the looks of it, something in the keypad status report handling is bugging out. 

Does this happen immediately on connection (i.e., during whatever initial information gathering M1 Touch Pro does), or does it happen after you do something in the app (if so, what was it)?

**Comment by JonGilmore** [comment]
It happens immediately upon connection of the app.  Certainly seems like your analysis is correct from my perspective as well.

**Comment by BioSehnsucht** [comment]
@jon102034050 I just released an update. Please let me know if it still disconnects when your Android app connects to the Elk.

**Comment by JonGilmore** [comment]
@BioSehnsucht hm, still seeing this issue.  Here's a small snippet of logs:

```2018-04-13 22:03:52 DEBUG (Thread-3) [PyElk.Elk] elk_queue_process - checking events
2018-04-13 22:03:52 DEBUG (Thread-3) [PyElk.Elk] elk_queue_process - Event.EVENT_KEYPAD_STATUS_REPORT
2018-04-13 22:03:52 DEBUG (Thread-3) [PyElk.Connection] handle_line: 19KC00000101120000000000013
2018-04-13 22:03:52 INFO (MainThread) [homeassistant.core] Bus:Handling <Event platform_discovered[L]: service=load_platform.sensor, platform=elkm1, discovered=[<PyElk.Keypad.Keypad object at 0x7f1d26375128>]>
2018-04-13 22:03:52 INFO (MainThread) [homeassistant.core] Bus:Handling <Event platform_discovered[L]: service=load_platform.switch, platform=elkm1, discovered=[<PyElk.Keypad.Keypad object at 0x7f1d26375128>]>
2018-04-13 22:03:52 INFO (MainThread) [homeassistant.core] Bus:Handling <Event platform_discovered[L]: service=load_platform.alarm_control_panel, platform=elkm1, discovered=[<PyElk.Keypad.Keypad object at 0x7f1d26375128>]>
2018-04-13 22:03:52 INFO (MainThread) [homeassistant.core] Bus:Handling <Event platform_discovered[L]: service=load_platform.climate, platform=elkm1, discovered=[<PyElk.Keypad.Keypad object at 0x7f1d26375128>]>
2018-04-13 22:03:52 INFO (MainThread) [homeassistant.core] Bus:Handling <Event platform_discovered[L]: service=load_platform.light, platform=elkm1, discovered=[<PyElk.Keypad.Keypad object at 0x7f1d26375128>]>
2018-04-13 22:03:52 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.elkm1
2018-04-13 22:03:52 INFO (MainThread) [homeassistant.components.switch] Setting up switch.elkm1
2018-04-13 22:03:52 INFO (MainThread) [homeassistant.components.alarm_control_panel] Setting up alarm_control_panel.elkm1
2018-04-13 22:03:52 INFO (MainThread) [homeassistant.components.climate] Setting up climate.elkm1
2018-04-13 22:03:52 INFO (MainThread) [homeassistant.components.light] Setting up light.elkm1
2018-04-13 22:03:52 DEBUG (Thread-3) [PyElk.Event] Parsing: '16RR5103176130418110006B'

2018-04-13 22:03:52 DEBUG (Thread-3) [PyElk.Elk] elk_queue_process - checking events
2018-04-13 22:03:52 DEBUG (Thread-3) [PyElk.Elk] elk_queue_process - Event.EVENT_RTC_REPLY
2018-04-13 22:03:52 DEBUG (Thread-3) [PyElk.Connection] handle_line: 16RR5103176130418110006B
2018-04-13 22:03:52 DEBUG (Thread-3) [PyElk.Event] Parsing: '17IC00000000000000000007C'

2018-04-13 22:03:52 DEBUG (Thread-3) [PyElk.Elk] elk_queue_process - checking events
2018-04-13 22:03:52 DEBUG (Thread-3) [PyElk.Elk] elk_queue_process - Event.EVENT_USER_CODE_ENTERED
2018-04-13 22:03:52 DEBUG (Thread-3) [PyElk.Connection] Lost connection```

**Comment by BioSehnsucht** [comment]
@jon102034050 Have you tried the new `gwww-elkm1-lib` branch? You'll have to make some config changes to switch to it, and entities and some attributes will have different names, so you might have to adjust sensor templates, automations, etc to test it - you might try with a second HASS instances if that's easier for you to test. It will eventually be the new master branch.

**Comment by JonGilmore** [comment]
unfortunately, I haven't been able to try it yet. Without going into too much detail, I was forced to move out of my home because of a fire. I expect to be back in in a few weeks, I'm stoked to get back at it!

**Comment by BioSehnsucht** [comment]
Sorry to hear that! Glad to hear it's only short term though.

**Comment by JonGilmore** [comment]
issue doesn't exist when using the gwww branch. sounds like that branch is the way this is moving in the future, so I think we'll close this out. thanks buddy!
